AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Orders Demo App DynamoDB Tables

  Sample SAM Template for AWS

Parameters:
  Environment:
    Description: Environment
    Default: dev
    Type: String
    AllowedValues:
      - prod
      - test
      - dev
    ConstraintDescription: Must specify a valid environment dev, test or prod.

Mappings:
  OrdersMap:
    table:
      name: order_demo_app_table

Resources:
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ["_", [!FindInMap [OrdersMap, table, name], !Ref 'Environment']]
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  OrdersTable:
    Description: "Orders table"
    Value: !Ref OrdersTable
  OrdersTableArn:
    Description: "Orders table ARN"
    Value: !GetAtt OrdersTable.Arn
